
-- 重置数据库

DROP TRIGGER IF EXISTS AfterUserInsert;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS UserInfos;
DROP TABLE IF EXISTS GroupsTable;
DROP TABLE IF EXISTS GroupMembers;
DROP TABLE IF EXISTS GroupMessages;
DROP TABLE IF EXISTS GroupFiles;